name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    timeout-minutes: 10
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - uses: dart-lang/setup-dart@v1

    - name: 'Fetch packages'
      run: flutter pub get
      
    - name: 'Analyze project'
      run: flutter analyze
      
    - name: 'Run tests'
      run: flutter test

    - name: 'Publish'
      run: dart pub publish --force